gaussian_blur_size: 5
gaussian_blur_sigma: 1.88
canny_edge_th: 189
hough_accum_resolution: 1
min_circle_dist: 136.8
hough_accum_th: 20.9
min_radius: 26
max_radius: 395
filter_h_min: 359
filter_h_max: 118
filter_s_min: 149
filter_s_max: 255
filter_v_min: 103
filter_v_max: 255
use_second_filter: false
filter2_h_min: 54
filter2_h_max: 359
filter2_s_min: 18
filter2_s_max: 85
filter2_v_min: 230
filter2_v_max: 255
ellipse_size: 2
filter_debug: false