!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  canny_edge_th: 189.0
  debug_image: true
  ellipse_size: 2
  filter2_h_max: 359
  filter2_h_min: 54
  filter2_s_max: 85
  filter2_s_min: 18
  filter2_v_max: 255
  filter2_v_min: 230
  filter_h_max: 118
  filter_h_min: 359
  filter_s_max: 255
  filter_s_min: 149
  filter_v_max: 255
  filter_v_min: 103
  gaussian_blur_sigma: 1.88
  gaussian_blur_size: 5
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      canny_edge_th: 189.0
      debug_image: true
      ellipse_size: 2
      filter2_h_max: 359
      filter2_h_min: 54
      filter2_s_max: 85
      filter2_s_min: 18
      filter2_v_max: 255
      filter2_v_min: 230
      filter_h_max: 118
      filter_h_min: 359
      filter_s_max: 255
      filter_s_min: 149
      filter_v_max: 255
      filter_v_min: 103
      gaussian_blur_sigma: 1.88
      gaussian_blur_size: 5
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      hough_accum_resolution: 1.0
      hough_accum_th: 10.0
      id: 0
      max_radius: 395
      min_circle_dist: 136.8
      min_radius: 26
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      state: true
      type: ''
      use_second_filter: false
    state: []
  hough_accum_resolution: 1.0
  hough_accum_th: 10.0
  max_radius: 395
  min_circle_dist: 136.8
  min_radius: 26
  use_second_filter: false
state: []
