gaussian_blur_size: 20
gaussian_blur_sigma: 4.300000190734863
canny_edge_th: 106
hough_accum_resolution: 1
min_circle_dist: 111
hough_accum_th: 24.70000076293945
filter_h_min: 94
filter_h_max: 133
filter_s_min: 57
filter_s_max: 255
filter_v_min: 63
filter_v_max: 255
use_second_filter: false
filter2_h_min: 66
filter2_h_max: 359
filter2_s_min: 113
filter2_s_max: 255
filter2_v_min: 181
filter2_v_max: 255
ellipse_size: 8
filter_debug: false